"""empty message

Revision ID: 56c26abd2e14
Revises: 
Create Date: 2023-08-24 18:00:32.208700

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '56c26abd2e14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('same_holder', sa.Boolean(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transaction_value', sa.Float(), nullable=False),
    sa.Column('transaction_time', sa.DateTime(), nullable=False),
    sa.Column('datetime_program', sa.DateTime(), nullable=True),
    sa.Column('customer_doc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('receptor_doc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_vendor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_longitude', sa.Float(), nullable=True),
    sa.Column('device_latitude', sa.Float(), nullable=True),
    sa.Column('device_memory', sa.Float(), nullable=True),
    sa.Column('device_cpu_count', sa.Integer(), nullable=True),
    sa.Column('device_cookies_enabled', sa.Boolean(), nullable=True),
    sa.Column('device_screen_resolution_x', sa.Integer(), nullable=True),
    sa.Column('device_screen_resolution_y', sa.Integer(), nullable=True),
    sa.Column('device_screen_orientation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactionanalysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prediction', sa.Float(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactionanalysis')
    op.drop_table('transaction')
    op.drop_table('rule')
    # ### end Alembic commands ###
