version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  server:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    image: superset-proxy-api
    restart: always
    env_file:
      - ./.envs/.env-dev
    container_name: superset-proxy-api
    command: >
      bash -c 'alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --timeout-keep-alive 10'
    # uncomment to simulate production
    # command: >
    #   bash -c 'gunicorn app.main:app -k uvicorn.workers.UvicornWorker -c deploy_conf.py'
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app/app
    networks:
      - superset-proxy-api
    extra_hosts:
      - "host.docker.internal:host-gateway" 
  db:
    image: postgres:14.2
    command: ["postgres", "-c", "max_connections=1000"]
    ports:
      - "5432:5432"
    volumes:
      - "./dockervolume/db/pgdata:/var/lib/postgresql/data"
    networks:
      - superset-proxy-api
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "fastapi-auth-db"

networks:
  superset-proxy-api:
    name: superset-proxy-api
