version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  server:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    image: base-fastapi
    restart: always
    env_file:
      - ./.envs/.env-dev
    container_name: base-fastapi
    command: >
      bash -c './scripts/migrate_all.sh && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --timeout-keep-alive 10'
    # uncomment to simulate production
    # command: >
    #   bash -c 'gunicorn app.main:app -k uvicorn.workers.UvicornWorker -c deploy_conf.py'
    volumes:
      - ./app:/usr/src/app/app
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway" 
  db:
    image: postgres:15
    command: ["postgres", "-c", "max_connections=1000"]
    env_file:
      - ./.envs/.env-dev
    network_mode: "host"
    volumes:
      - "./dockervolume/db/pgdata:/var/lib/postgresql/data"
      - ./scripts/create_databases.sh:/docker-entrypoint-initdb.d/create_databases.sh
    environment:
      POSTGRES_PASSWORD: "postgres"
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    command: ["start-dev"]
    restart: always
    network_mode: "host"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://localhost:5432/keycloakdb
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_HOSTNAME: localhost
      KC_HEALTH_ENABLED: "true"

