version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  # server:
  #   build:
  #     context: .
  #     dockerfile: ./docker/dev/Dockerfile
  #   image: base-fastapi
  #   restart: always
  #   env_file:
  #     - ./.envs/.env-dev
  #   container_name: base-fastapi
  #   command: >
  #     bash -c './scripts/migrate_all.sh && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --timeout-keep-alive 10'
  #   # uncomment to simulate production
  #   # command: >
  #   #   bash -c 'gunicorn app.main:app -k uvicorn.workers.UvicornWorker -c deploy_conf.py'
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./app:/usr/src/app/app
  #   networks:
  #     - base-fastapi-network
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway" 
  db:
    image: postgres:15
    command: ["postgres", "-c", "max_connections=1000"]
    env_file:
      - ./.envs/.env-dev
    ports:
      - "5432:5432"
    volumes:
      - "./dockervolume/db/pgdata:/var/lib/postgresql/data"
      - ./scripts/create_databases.sh:/docker-entrypoint-initdb.d/create_databases.sh
    networks:
      - base-fastapi-network
    environment:
      POSTGRES_PASSWORD: "postgres"
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    command: ["start-dev"]
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

networks:
  base-fastapi-network:
    name: base-fastapi-network
